name: geolocator_linux
description: Geolocation Linux plugin for Flutter. This plugin provides the
  Linux implementation for the geolocator.
repository: https://github.com/baseflow/flutter-geolocator/tree/main/geolocator_linux
issue_tracker: https://github.com/baseflow/flutter-geolocator/issues?q=is%3Aissue+is%3Aopen
version: 0.2.4
publish_to: none

environment:
  sdk: ^3.11.0
  flutter: ">=3.41.0"

flutter:
  plugin:
    implements: geolocator
    platforms:
      linux:
        dartPluginClass: GeolocatorLinux

dependencies:
  dbus: ^0.7.12
  flutter:
    sdk: flutter
  geoclue: ^0.1.1
  geolocator_platform_interface:
    git: https://github.com/kumsumit/geolocator_platform_interface.git
  gsettings: ^0.2.8
  package_info_plus: "^9.0.0"

dev_dependencies:
  build_runner: ^2.11.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.6.3
  plugin_platform_interface:
    git: https://github.com/kumsumit/plugin_platform_interface.git
